language: python
python:
    - "2.7"
sudo: false
install:
    - pip install -r requirements.txt
    - pip install -r test_requirements.txt
    - npm install -g css-lint
script:
    - ./run_tests_with_coverage.sh
after_success:
    - coveralls
